import { CategoriesGrid } from '../categories-grid';

// 50 : 16

export const metadata = {
  title: 'Categories - Layer Streetwear',
  description: 'Generated by create next app',
};

const CategoriesPage = () => {
  return <CategoriesGrid />;
};

export default CategoriesPage;
